### ISSUE TITLE
使用浏览器请求的时候 会发生发送空包的情况

### ISSUE THREAD

**Issue by xiantang** [xiantang/XServer#1]
```java
Exception in thread "Thread-0" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at info.xiantang.basic.http.Request.parseRequestInfo(Request.java:95)
	at info.xiantang.basic.http.Request.<init>(Request.java:55)
	at info.xiantang.basic.core.network.dispatcher.nio.NioDispatcher.doDispatch(NioDispatcher.java:27)
	at info.xiantang.basic.core.network.endpoint.nio.NioEndpoint.execute(NioEndpoint.java:93)
	at info.xiantang.basic.core.network.connector.nio.NioPoller.processSocket(NioPoller.java:87)
	at info.xiantang.basic.core.network.connector.nio.NioPoller.run(NioPoller.java:63)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by xiantang** [comment]
空包是用来判断服务端是否仍在线，在请求头包含keep-alive 的情况下 就会由客户端 不断发送空包
